server:
  port: 8091

#DB
spring:
  cloud:
    azure:
      credential:
        managed-identity-enabled: true
        client-id: 11111111-1111-1111-1111-111111111111
  datasource:
    url: jdbc:postgresql://localhost:5432/contacts
    username: contacts-workload-id
    azure:
      passwordless-enabled: true
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
    change-log: db/changelog.xml
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8090/realms/vision-notes/protocol/openid-connect/certs
#          audiences: vision-notes


#DB
logging:
  level:
    root: INFO