server:
  port: 8091

#DB
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/prm
    username: postgres
    password: test
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
    change-log: db/changelog.xml
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8090/realms/prm
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8090/realms/prm
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: prm-backend
            authorization-grant-type: authorization_code
            scope: openid


#DB
logging:
  level:
    root: INFO