server:
  port: 8091

#DB
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/prm
    username: postgres
    password: test
  jpa:
    hibernate:
      ddl-auto: create-drop
  liquibase:
    enabled: false
    change-log: db/changelog.xml

#DB
logging:
  level:
    root: INFO