services:
  postgres:
    image: postgres:16.2
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=postgres
      - POSTGRES_DB=contacts
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
    volumes:
      - prm_data:/var/lib/postgresql/data
  keycloak:
    image: docker.io/bitnami/keycloak:25.0.5-debian-12-r0
    restart: unless-stopped
    environment:
      KEYCLOAK_DATABASE_NAME: contacts
      KEYCLOAK_DATABASE_USER: postgres
      KEYCLOAK_DATABASE_PASSWORD: test
      KEYCLOAK_DATABASE_HOST: "postgres"
      KEYCLOAK_ENABLE_STATISTICS: true
      KEYCLOAK_LOG_LEVEL: INFO
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: test
      #      KEYCLOAK_HOSTNAME: development.local
      KEYCLOAK_PRODUCTION: true
      KEYCLOAK_ENABLE_HTTPS: true
      KEYCLOAK_HTTPS_USE_PEM: true
      KEYCLOAK_HTTPS_CERTIFICATE_FILE: /opt/bitnami/keycloak/certs/tls.crt
      KEYCLOAK_HTTPS_CERTIFICATE_KEY_FILE: /opt/bitnami/keycloak/certs/tls.key
      KEYCLOAK_EXTRA_ARGS: --import-realm
    ports:
      - 8090:8080
      - 8443:8443
    volumes:
      - ./keycloak/realm.json:/opt/bitnami/keycloak/data/import/realm.json:ro
      - ./ssl/development.local.crt:/opt/bitnami/keycloak/certs/tls.crt
      - ./ssl/development.local.key:/opt/bitnami/keycloak/certs/tls.key
    depends_on:
      - postgres
volumes:
  prm_data:
    driver: local

